ARG CONTAINER_VERSION=25.10-py3
FROM nvcr.io/nvidia/pytorch:${CONTAINER_VERSION}
LABEL maintainer="Juan Treminio <jtreminio@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update &&\
    apt install -y ccache libsox-dev libavformat-dev libavcodec-dev libavutil-dev libavdevice-dev ffmpeg libavfilter-dev libswresample-dev libswscale-dev &&\
    apt-get autoclean &&\
    apt-get -y --purge autoremove &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/{man,doc}

RUN pip install -U setuptools \
    cmake \
    cupy-cuda13x \
    cuda-python \
    ninja \
    nvidia-ml-py \
    pybind11 \
    pynvml>=12.0.0 \
    sentencepiece \
    soundfile \
    torchcodec
